name: Build & Publish MSI

on:
  push:
    tags:
      - 'v*'   # es. v1.0.0, v1.1.5 ecc.

jobs:
  build-msi:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Temurin JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Install WiX Toolset (per jpackage)
        run: choco install wixtoolset --yes

      - name: Build MSI package
        run: mvn -B clean package -DskipTests

      - name: Lista risultati
        run: |
          echo "Contenuto di target/"
          dir target

      - name: Upload artefatti in Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/IsyGateClient-*.msi
            target/app/**
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Fine
        run: echo "✅ Build MSI completata e pubblicata!"
